### ISSUE TITLE
add fields to query builder

### ISSUE THREAD

**Issue by smarques** [stephpy/timeline-bundle#165]
It would be nice to be able to extend the query builder and add custom fields, so that you can set criterias on the new field as well.

I tried by extending querybuilder, like so:

```
    namespace Acme\myBundle\Timeline;

   use Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder as BaseQueryBuilder;
   use Symfony\Component\OptionsResolver\OptionsResolver;
   use Spy\Timeline\Driver\QueryBuilder\Criteria\CriteriaInterface;

   class QueryBuilder extends BaseQueryBuilder
   {

    /**
     * @var array
     */
    protected static $fieldLocation = array(
        'context'    => 'timeline',
        'MY_CUSTOM_FIELD'    => 'action',
        'createdAt'  => 'action',
        'verb'       => 'action',
        'type'       => 'actionComponent',
        'text'       => 'actionComponent',
        'model'      => 'component',
        'identifier' => 'component',
    );

.......
    public function getAvailableFields()
    {
        return array(
            'context',
            'verb',
            'createdAt',
            'type',
            'text',
            'model',
            'identifier',
            'MY_CUSTOM_FIELD'
        );
    }
}
```

The problem is that here
https://github.com/stephpy/timeline-bundle/blob/93929f14f151e2c19b4d7d4c81001dad89efe68f/Driver/ORM/QueryBuilder/Criteria/CriteriaField.php#L43

you have

```
  $this->location    = QueryBuilder::getFieldLocation($field);
```

and the static call goes direct to the parent object and the field I added is ignored and, sadly,  I get an error.

Is there  better way to add fields and use them in the query builder?

Thanks in advance
sergio

**Comment by stephpy** [comment]
Fixed on https://github.com/stephpy/timeline/commit/270648b6f4432f3c24b8ecacd825f7f7f4de7492 

With a big lag ... sorry.

**Comment by smarques** [comment]
👍  💚
