### ISSUE TITLE
Add ability to use multiple drivers

### ISSUE THREAD

**Issue by toinouu** [stephpy/timeline-bundle#172]
Hi @stephpy ,

I wonder if it was possible to add ability to use  ODM and ORM in the same application.

The goal would be to use ODM for TimelineBundle and ORM for SonataTimelineBundle.

Thank you

**Comment by stephpy** [comment]
Hi,

It'sn't possible at this time. :\

It should be hard to implement but if you want to do it, i accept PRs. :D
