### ISSUE TITLE
Adding new field

### ISSUE THREAD

**Issue by MyOpla** [stephpy/timeline-bundle#173]
Hi,
Please I need to add new field in Component entity.
How can I do it ?

**Comment by MyOpla** [comment]
any ideas please ?

**Comment by stephpy** [comment]
Hi,

You should look at documentation on doctrine orm. It's easy, you only have to add some annotations & properties in your component class. This is not about TimelineBundle.

**Comment by MyOpla** [comment]
I know how to work with doctrine orm... and I did it but it doen't work, this why I'm asking if there is something about TimelineBundle.

this is my entity : 
namespace Sonata\TimelineBundle\Entity;

use Spy\TimelineBundle\Entity\Component as BaseComponent;
use Doctrine\ORM\Mapping as ORM;
/**
 * Component entity for Doctrine ORM.
 *
 * @uses BaseComponent
 */
class Component extends BaseComponent
{
 /**
     * @var integer
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=100)
     */
    private $code;
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
}

I can't generate getters and setters and I can't update schema

**Comment by stephpy** [comment]
You setted an @orm\Column on `public function getId()` ? Or there is a mistake on copy/paste

**Comment by MyOpla** [comment]
Sorry, it's not passed correctly;

namespace Application\Sonata\TimelineBundle\Entity;

use Spy\TimelineBundle\Entity\Component as BaseComponent;
use Doctrine\ORM\Mapping as ORM;


class Component extends BaseComponent
{

/**

*@var integer
* /

protected $id;

/ **
* @var string

*@ORM\Column(name="code", type="string", length=100) 
* / 

private $code; 

/ **
*@var integer
* /

public function getId() 
{ return $this->id; } 

}


My problem is with the field "code"

**Comment by stephpy** [comment]
have you any error ?

I still think it's a doctrine “issue“.

**Comment by MyOpla** [comment]
I don"t have any error.
In doctrine they says that the entity extends a mapped superclass. I thing Spy\TimelineBundle\Entity\Component is a superclass ?
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#overrides

Well I don't know...

**Comment by stephpy** [comment]
I'm sorry, i can't help.
I use mapped super class and overriding attributes all day and i have not any problem. You have probably missed something ...
