### ISSUE TITLE
Post to own wall directly but queue the spread

### ISSUE THREAD

**Issue by robbanl** [stephpy/timeline-bundle#175]
Hi,

I've configured my spread delivery to "wait". With this behavior, I noticed that the post isn't available at my own user until it's spread.

If my user has 500 connections (that should receive the spread), I'd like to directly publish the note on my own wall, and then let a separate worker handle the spread to the rest of the 500 users.

Is it possible or did I miss some crucial documentation?

Fetching the timeline this way:

            $actionManager = $this->get('spy_timeline.action_manager');
            $timelineManager = $this->get('spy_timeline.timeline_manager');
            $subject = $actionManager->findOrCreateComponent($myUserObject);
            $timeLine = $timelineManager->getTimeline($subject);

Thanks otherwise for a GREAT bundle!

**Comment by stephpy** [comment]
Hi,

You could get directly actions of user with `getSubjectActions`.

But if you want to get the `wall` of the users (its actions and actions of its connections),  it uses spread system for user itself and its connections. At this moment, we cannot choose to delivery “immediatly“ some spread then “wait“ for some others, sorry.

**Comment by robbanl** [comment]
No problem! I'll give `getSubjectActions` a try! Thanks for a quick reply!
