### ISSUE TITLE
Only one subject is loaded

### ISSUE THREAD

**Issue by robbanl** [stephpy/timeline-bundle#176]
I fetch the timeline for each user like this ($currentUser = \AppBundle\Entity\User)

```
$actionManager = $this->get('spy_timeline.action_manager');
$timelineManager = $this->get('spy_timeline.timeline_manager');
$subject = $actionManager->findOrCreateComponent($currentUser);
$timeLine = $timelineManager->getTimeline($subject);
```

Everything looks good in the database from what I can see.

Now, both User:1 and User:2 adds own time line entries and they are spread to each other.

When looking through User:1, I can see both self and other but the other entity isn't loading correctly. Switching user gives the same problem, but then I can't see User:1's username.

Is there any way to debug what class is being loaded to see what's going wrong and where? Or any other ideas?

Thanks in advance!

**Comment by stephpy** [comment]
Hi,

Do you use [DataHydrator filter](https://github.com/stephpy/timeline-bundle/blob/master/Resources/doc/filter.markdown#datahydrator) ?

If yes and it still not load some entities, you can look at [this locator](https://github.com/stephpy/timeline-bundle/blob/master/Filter/DataHydrator/Locator/DoctrineORM.php) to try to know why entities aren't loaded. There is no more debug tools than it.

**Comment by robbanl** [comment]
I was missing the DataHyrator filter... Thank you very much for your quick assist!
