### ISSUE TITLE
Timeline listing in sonataadmin bundle

### ISSUE THREAD

**Issue by nepfrank** [stephpy/timeline-bundle#180]
I am using sonata timeline bundle(which in turn uses this bundle).
I was planning to have a normal actions list page with pagination and some filters.(just like post listing page) but i am totally confused how to get it donw

For normal bundle we made admin controller as follows. But for timeline i don't know what to do. I was able to get some record on dashboard but i want to keep all records as activity log.

What should i do?

class TimelineAdmin extends Admin
{
    /**
     * {@inheritdoc}
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('...')
        ;
    }

    /**
     * {@inheritdoc}
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('...')
        ;
    }
}

**Comment by stephpy** [comment]
You should create this issue in Sonata/TimelineBundle. I didn't use it, i can't answer to you.
