### ISSUE TITLE
Incorect internal Pager reference

### ISSUE THREAD

**Issue by sadortun** [stephpy/timeline-bundle#182]
Bonjour Stéphane,

The following code should return both timelnes from Subject A and B, but they return two time the Subject B timeline.

``` php
$timelineA = $timelineManager->getTimeline($subjectA );
$timelineB = $timelineManager->getTimeline($subjectB);
```

When disabling the pagination, the expected timelines are retrived :

``` php
$timelineA = $timelineManager->getTimeline($subjectA , array('paginate' => false) );
$timelineB = $timelineManager->getTimeline($subjectB , array('paginate' => false));
```

I havent dig to deep in the timeline internals, but I think the internal reference to to the paginator / resultBuilder orshould be cloned.
https://github.com/stephpy/timeline-bundle/blob/master/Driver/ORM/Pager.php#L55

Thanks,
Samuel

**Comment by stephpy** [comment]
Hi,

Looks ok, did you try to use clone ? Is it work ?

**Comment by sadortun** [comment]
No, i have not investigated further. I was waiting for your feedback before going too deep. ( I try to avoid messing with the bundle internals of others when i installed it one hour ago :) ) 

I'll do some testing and get back to you in a few days.

**Comment by stephpy** [comment]
I guess you're right about clone. Tell me if it fix your issue please. :)
