### ISSUE TITLE
Unresolved References

### ISSUE THREAD

**Issue by chugas** [stephpy/timeline-bundle#183]
I have an Entity User with a field deleted of type boolean. When I want to remove a User I set 
deleted = 1. I would like to know how can I filter this in the results of the timeline.

For Example:

\Entity\User:1 | comment | \Entity\Article:2 | of | \Entity\User:2
\Entity\User:2 | comment | \Entity\Article:7 | of | \Entity\User:1
\Entity\User:1 | comment | \Entity\Article:7 | of | \Entity\User:3

Table User
id  | name  | deleted
1  | Ana     | 0
2  | Maria  | 1
3  | Jose    | 0 

and expected result:

\Entity\User:1 | comment | \Entity\Article:7 | of | \Entity\User:3

**Comment by stephpy** [comment]
Hi,

You could add a [POST filter](https://github.com/stephpy/timeline-bundle/blob/master/Resources/doc/filter.markdown#adding-a-filter), or more globally a Doctrine filter as Gedmo SoftDeletable does.

**Comment by chugas** [comment]
Thank you!

**Comment by stephpy** [comment]
You're welcome. :)
