### ISSUE TITLE
How to use spread and timeline?

### ISSUE THREAD

**Issue by berdyshev** [stephpy/timeline-bundle#185]
Hi, I'm trying to understand how to use a timeline, but it's difficult, because a lot of things are not described in documentation. So, I will list here couple of questions and will be glad if you could help me:

1. What is difference between Entry and EntryUnaware in Spread? Where should I use them? I used EntryUnaware to "notify" user's friends about his new friend, but this action didn't appeared in user's friends' timelines. Why?
2. There is possibility to pass array of IDs as second argument of EntryUnaware — what is difference if I create new EntryUnaware for each ID or I create single EntryUnaware with array of IDs.
3. Is there possibility to get user's timeline for two (or even all)  contexts at once?
4. To create new Entry (within new Component — friends of the current user) I need to have ActionManager. When I inject it as argument to the service of spread I get error about circular dependencies, so do I need to inject entire Container or there is another way to get ActionManger from $action or $coll arguments of proccess() method?

Thanks a lot for any help.

**Comment by stephpy** [comment]
Hi,

> What is difference between Entry and EntryUnaware

When you deploy action to friends, you could choose to not fetch entities of theses friends.
Imagine you have to deploy to 500 users, and you have not theses 500 users fetched from database. You will be able to provide an array of 500 `EntryUnaware` with only the class and identifier. If you use `Entry`, you will have to fetch theses users.

> but this action didn't appeared in user's friends' timelines. Why?
May be my previous answer would fix it ? 

> 2) There is possibility to pass array of IDs as second argument of EntryUnaware — what is difference if I create new EntryUnaware for each ID or I create single EntryUnaware with array of IDs.

An array of id is for composite keys only. ONE instance of EntryUnaware is for ONE entity.

> 3) Is there possibility to get user's timeline for two (or even all) contexts at once?

Sure, you will have to use `QueryBuilder` (see documentation), but it's a bit difficult. Or try to understand how timelines and actions work to create your own sql query.

> 4) You could use `EntryUnaware`. Or yes, you have to inject container :(. At this moment, we do not provide entityManager with spread system.

You're welcome.

**Comment by berdyshev** [comment]
Thanks a lot, Stéphane, for your so fast response.

I've just tried to create array of EntryUnaware for each friend, but it doesn't work somehow. If I create just  Entry for each friend - it works, but for EntryUnaware - not. 

Here is my process() code:

```php
        /** @var User $user */
        $user = $action->getSubject()->getData();
        $user2Id = $action->getComponent('complement')->getIdentifier();

        foreach ($user->getFriends() as $friend) {
            $friendId = $friend->getUser2()->getId();
            if ($friendId != $user->getId() && $friendId != $user2Id) {
                $entry = new EntryUnaware(self::USER_CLASS, $friendId);
                $coll->add($entry, 'FRIENDS');
            }
        }
```

**Comment by berdyshev** [comment]
Sorry, it was my mistake — wrong Model name in USER_CLASS
