### ISSUE TITLE
Database deleted by accident

### ISSUE THREAD

**Issue by semiaLi** [stephpy/timeline-bundle#193]
Good morning,
While i was working i have deleted my base by accident. I have recreate it with the backend i have created but my problem is that the data in relation with the bundle aren't shown .
The table timeline is full but in the query builder result is empty :(

**Comment by stephpy** [comment]
Hi,

Action table is OK ? Components ? 
If you activated the DataHydrator with `filter_unresolved` attribute, the data of component should exist too ...

Complicated to say what's going wrong.

**Comment by semiaLi** [comment]
Yes the action table and the component table are ok :(
spy_timeline:
    paginator: spy_timeline.paginator.knp
    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    true
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:  TimeLineBundle\Entity\Timeline
                action:    TimeLineBundle\Entity\Action
                component: TimeLineBundle\Entity\Component
                action_component: TimeLineBundle\Entity\ActionComponent

I am blocked i don't know what to do :(

**Comment by semiaLi** [comment]
Thank you , there was a fault in the component table , it has deleted th \ in the model so it hasn't know the origin of component data :)

**Comment by stephpy** [comment]
:)
