### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dincho** [stephpy/timeline-bundle#198]
Symfony 3 is latests stable. 
I see there is support on master but there is no tagged version.

Is there something left that needs to be done for 3.0 support?

**Comment by stephpy** [comment]
No feedback since we allowed 3.x, I guess it's ok.https://github.com/stephpy/timeline-bundle/releases/tag/2.3.0 ;)

**Comment by dincho** [comment]
Huh, are you released this today? Github says Dec 3, 2015, but I'm pretty sure I checked before opening this.

**Comment by stephpy** [comment]
I just released it, yes ;)

**Comment by stephpy** [comment]
Github uses the last commit date

**Comment by dincho** [comment]
I didn't knew that. Thank you!

**Comment by cbeyer** [comment]
Hi @dincho , does this bundle works with your Symfony 3 installation ?

**Comment by dincho** [comment]
@cbeyer Well, it was almost 2 years ago. Probably it did :)

**Comment by cbeyer** [comment]
I asked because for me it doesnt work, if you can see here https://github.com/stephpy/timeline-bundle/issues/208 Thanks :)
