### ISSUE TITLE
Foreign Key Relationships ?

### ISSUE THREAD

**Issue by jayesbe** [stephpy/timeline-bundle#199]
I have just tested user deletion scenarios and I am seeing the timeline bomb all over the place with various users that have interactions with others whom have now been hard deleted using MySQL DB level cascading.  I am wondering what the best scenario would be to handle this?

Option1:
I am assuming that I need to iterate through the timeline information of the user that has been deleted and remove those entries from the currently existing users.  

Option2: 
Add soft delete to Users so they are never actually removed. (I don't like this option)

**Comment by stephpy** [comment]
Hi,

Did you see this part of documentation ? https://github.com/stephpy/timeline-bundle/blob/master/Resources/doc/filter.markdown#removing-actions-with-unresolved-references

If you have references to unresolved components (softdeleted or harddeleted resources), action will be dropped automatically from the list (your option 1).

**Comment by jayesbe** [comment]
Thanks you.

**Comment by stephpy** [comment]
You're welcome.
