### ISSUE TITLE
Warning: array_merge() expects at least 1 parameter, 0 given

### ISSUE THREAD

**Issue by axzx** [stephpy/timeline-bundle#205]
`vendor/stephpy/timeline-bundle/DependencyInjection/Compiler/AddSpreadCompilerPass.php:26`

```
 [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
                                                                             
    [Symfony\Component\Debug\Exception\ContextErrorException]                
    Warning: array_merge() expects at least 1 parameter, 0 given 
```

**Comment by 7thcubic** [comment]
What is your config used for spreader ?

Only single spreader used?
I submitted a PR that fixed issue with conflicting priority spread.

**Comment by axzx** [comment]
I haven't any spreads

**Comment by 7thcubic** [comment]
There is a minimum requirement of having One Spreader class for this to work actually.

Have to look into how i can fix it so that there will be no exception when there is no spreader.

**Comment by stephpy** [comment]
I merged your fix, thanks.
